### ISSUE TITLE
Double tap to chek/wake

### ISSUE THREAD

**Issue by XxDinoCraftxX** [blckbearx/AOD-Enabler#1]
The module works perfectly, but you can add the option of double tap to check, double tap in the notification of song to skip, and lift to wake
I'm just giving you an idea, the module currently has no problem in Pixel Experience Plus 10 on Moto G5 cedric :)
PS: the old module that changed the accent color in android 10 had all those options but the only bug was the blue accent color

**Comment by blckbearx** [comment]
Hi, thanks for the feedback!
Regarding double tap and lift to wake and music skipping, those options are ROM dependant, meaning that implementing those varies from ROM to ROM and sometimes need kernel implementation (DT2W for example) so theres no simple and generic way I could achieve that as far as I know.
