### ISSUE TITLE
Android 10 support?

### ISSUE THREAD

**Issue by V3ntus** [blckbearx/AOD-Enabler#2]
Device: hammerhead
Magisk v20.4
TWRP: 3.4.0-HH.R.7
ROM: crDroid 6.12

Installing via TWRP:
```
- Mounting /system...
! Cannot mount /system
- Unmounting partitions
Update process ended with ERROR: 123
E: Error creating fstab
```

Installing via Magisk:
Seems to show successful install, yet does not appear in the modules list before or after reboot.

**Comment by blckbearx** [comment]
This is a Substratum module that installs as a normal app (it's an APK). You should install substratum (or substratum lite if youre on android 10) and enable substratum in magisk. Then you can build and enable the substratum module inside substratum.
Check the releases page for the download.
